foods = [
    u'Bacon', u'Bacon, egg and cheese', u'Baked bean', u'B\xe1nh m\xec',
    u'Barbecue', u'Barros Jarpa', u'Barros Luco', u'Bauru', u'Beef on weck',
    u'BLT', u'Bologna sandwich', u'Bosna', u'Breakfast roll', u'Breakfast',
    u'British Rail', u'Broodje kroket', u'Bun kebab', u'Butterbrot', u'Cemita',
    u'Chacarero', u'Cheese', u'Cheese and pickle', u'Cheesesteak',
    u'Chicken salad', u'Chickpea salad', u'Chili burger', u'Chip butty',
    u'Chipped beef', u'Chivito', u'Chow mein', u'Churrasco',
    u'Club', u'Corned beef', u'Crisp', u'Croque-monsieur', u'Cuban',
    u'Cucumber', u'Cudighi', u'Dagwood', u'Deli sandwich', u'Denver',
    u'Doner kebab', u'Donkey burger', u'Doubles', u'Dynamite',
    u'Dyrl\xe6gens natmad', u'Elvis sandwich', u'Egg', u'Fairy bread',
    u'Falafel', u'Fischbrtchen', u"Fool's Gold Loaf", u'Fluffernutter',
    u'Francesinha', u'Francesinha poveira', u'French dip', u'Fried brain',
    u'Ftira', u'Gatsby', u'Gerber', u'Guajolota', u'Gyro',
    u'Hagelslag or vlokken', u'Ham', u'Ham and cheese', u'Ham and egg bun',
    u'Hamburger', u'Hamdog', u'Horseshoe', u'Hot brown', u'Hot chicken',
    u'Hot dog', u'Hot turkey', u'Ice cream', u'Italian beef', u'Italiano',
    u'Jam', u'Jambon-beurre', u'Jibarito', u'Jucy Lucy', u'Katsu sando',
    u'Kokoretsi', u'Kottenbutter', u'Lettuce',
    u'Limburger sandwich', u'Lobster roll', u'Lox', u'Luther burger',
    u'Marmite', u'Martino', u'Meatball', u'Medianoche', u'Mitraillette',
    u'Melt', u'Mettbr\xf6tchen', u'Mollete', u'Montadito', u'Monte Cristo',
    u'Montreal-style smoked meat', u'Mortadella', u'Mother-in-law',
    u'Muffuletta', u'Beschuit met muisjes', u'Naan sandwich',
    u'Open-faced sandwich', u'Pambazo', u'Pan-bagnat', u'Panini',
    u'Patty melt', u'Peanut butter and jelly', u'Pebete', u'Pistolette',
    u'Pljeskavica', u"Ploughman's lunch", u"Po' boy", u'Polish boy',
    u'Porilainen', u'Pork chop bun', u'Pork tenderloin', u'Prawn roll',
    u'Primanti', u'Prosperity Sandwich', u'Pudgy Pie', u'Pulled pork sandwich',
    u'Reuben', u'Roti john', u'Rou jia mo', u'Runza', u'Sandwich loaf',
    u'De miga', u'Salt beef bagel', u'Sausage', u'Shawarma', u'Slider',
    u'Sloppy joe', u'Sloppy joe (New Jersey)', u"S'more",
    u'Sol over Gudhjem',
    u'Souvlaki', u'Spiedie', u'St. Paul', u'Steak bomb', u'Steak',
    u'Submarine/Sub sandwich/Baguette', u'Tavern', u'Tea', u'The Scooch',
    u'TLT (Tempeh, Lettuce, and Tomato)', u'Toast', u'Toast Hawaii',
    u'Toastie', u'Tofu Sandwich', u'Tongue toast', u'Torta', u'Torta ahogada',
    u'Tramezzino', u'Tripleta', u'Tuna', u'Vada pav', u'Vegemite',
    u'Vegetable', u'Welsh rarebit', u'Wrap', u'Wurstbrot (sausage bread)',
    u'Yakisoba-pan', u'Zapiekanka'
]

foods_extra = [
    u'Bread', u'Salad', u'Pain aux chocolats', u'Croissant', u'Sauce soga',
    u'Sauce tomate', u'coffee', u'ice cream'
]
